### ISSUE TITLE
活動刪除

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#10]
刪除按鈕放置到上一級：
![image](https://github.com/UM-ARK/ARK-ALL-Web/assets/55580370/571f9bd6-6137-4d5f-91d9-600e4c99f366)

刪除功能添加確認提醒，以防用戶誤觸刪除無法反悔

**Comment by YanzhenHuang** [comment]
1.刪除確認已完成。
2.刪除按鈕放到上一級不符合一般邏輯。先點編輯后點刪除更符合用戶直覺，故不作改動。
