### ISSUE TITLE
解決首頁的性能問題

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#21]
可能因動畫造成
![image](https://github.com/user-attachments/assets/3898a82a-6c10-4ebc-b183-d17370b0538b)

可考慮使用漸變或純色替代。

頂部毛玻璃切換有卡頓

**Comment by YanzhenHuang** [comment]
降低Blur濾鏡背後圖片的清晰度為128x128
