### ISSUE TITLE
PNG圖片背景透明問題

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#24]
PNG類型的透明背景圖片，如果遇到與背景色相近的情況，將完全看不清圖片內容。
需為圖片增加背景色。
<img width="1464" alt="截屏2024-07-31 12 33 23" src="https://github.com/user-attachments/assets/49e4de92-40c6-46e2-ac84-4529dfba0bf2">

<img width="1464" alt="截屏2024-07-31 12 34 57" src="https://github.com/user-attachments/assets/395b0c26-dab6-4f26-8ad8-87919e4d6f40">
↑增加了背景色的情況

**Comment by YanzhenHuang** [comment]
這是圖片提供者的問題。無法保證背景顏色對每個透明png都適用。themeColorUltraLight已經適用於大部分png圖片。如果需要完美效果，可以後續引入顔色處理包。
