### ISSUE TITLE
反饋浮窗

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#25]
功能仍無法正常使用，可以作為反饋窗口，直接向 umacark@gmail.com 反饋郵件。
![image](https://github.com/user-attachments/assets/d487ca9b-cc53-4d55-88e3-f0089f4f2387)

**Comment by yyyyyyounger** [comment]
可考慮在常見問題，註冊說明，直接建立電郵範本，幫助用戶快速註冊

**Comment by YanzhenHuang** [comment]
需要提供SMTP服務器。

**Comment by yyyyyyounger** [comment]
> 需要提供SMTP服務器。

簡單來 mailto: 吧

**Comment by YanzhenHuang** [comment]
mailto只会弹出用户的邮件弹窗

**Comment by yyyyyyounger** [comment]
6b1813e31b61f061983318914e02d42278894799
6d16f2662cd17660fdb15dc4f3728f92c87b3900
已修改為點擊跳轉Email
