### ISSUE TITLE
社團活動編輯頁 - 提示圖片可拖拽上傳

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#26]
![image](https://github.com/user-attachments/assets/1d5afb6a-10ea-40cc-ab13-985683c94abd)

**Comment by YanzhenHuang** [comment]
![image](https://github.com/user-attachments/assets/9c01efdc-9c1c-468d-8ad8-9107ffd5fc9c)

封面拖曳提示完成
