### ISSUE TITLE
社團信息編輯頁 - 聯繫方式需要固定可輸入的項目

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#29]
![image](https://github.com/user-attachments/assets/71a62ef4-30b8-4beb-9460-aa06da83407a)

APP
![b59e4514ece169b71d9a723b70bdbb7](https://github.com/user-attachments/assets/75f51c51-bb20-45ad-9c69-afec477cfefb)

**Comment by YanzhenHuang** [comment]
趕工中。。。
