### ISSUE TITLE
社團資訊編輯頁 - 沒有圖片刪除的可視按鈕

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#31]
![image](https://github.com/user-attachments/assets/0d9a7ff1-14a5-46a4-8aa2-709424689c16)

**Comment by YanzhenHuang** [comment]
![Snipaste_2024-08-11_03-06-58](https://github.com/user-attachments/assets/fea728e8-10d3-404a-867a-000f5c42e930)
添加文字提示
