### ISSUE TITLE
社團資訊編輯頁 - 聯繫方式需唯一，且提供默認選項

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#33]
目前沒有默認選項也能直接提交空白
![image](https://github.com/user-attachments/assets/aaea201b-5a3c-4201-b92f-9563ffa7f0dd)

會導致渲染的效果不行
![image](https://github.com/user-attachments/assets/5ef34db1-3c18-4f3f-8709-0206a0a58029)

**Comment by YanzhenHuang** [comment]
![image](https://github.com/user-attachments/assets/3722a3bd-042b-41d8-b988-0385bd7dfced)
已寫死
