### ISSUE TITLE
新建活動頁 時間設定提示

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#6]
Alert提示“結束時間應在開始之後”更佳。

![image](https://github.com/UM-ARK/ARK-ALL-Web/assets/55580370/e0ad967c-244f-4d6e-9d6b-8645b440b09b)

日期、時間輸入初應有即時的錯誤提示，不要等到本地保存才提示。

**Comment by YanzhenHuang** [comment]
那还要引入一个新的state

**Comment by yyyyyyounger** [comment]
> 那还要引入一个新的state

不用，直接在render裡面 `{}` 判斷就可以

**Comment by YanzhenHuang** [comment]
提示詞改了，但是實時提示就算了。感覺用處不大，不如維持現狀
