### ISSUE TITLE
編輯頁面上傳成功後自動返回並刷新

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#8]
如題，編輯頁面上傳成功後應該幫助用戶返回主頁或是上一頁，並刷新頁面，以免重複提交

**Comment by yyyyyyounger** [comment]
使用JS原生 `window.location.href = ./xxx/xxx";` 可以導航至相關頁面，或者使用router的back等方法

**Comment by YanzhenHuang** [comment]
有問題，跳轉不了，待研究

**Comment by YanzhenHuang** [comment]
完成
