### ISSUE TITLE
圖片默認背景問題

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/ARK-ALL-Web#9]
.png透明背景圖片容易導致深色模式下黑成一團，建議提供一個默認背景色，APP端為白色
![image](https://github.com/UM-ARK/ARK-ALL-Web/assets/55580370/a7b0cb8a-4a01-4ba6-96f2-530c5e886bec)

**Comment by yyyyyyounger** [comment]
深色模式下
![image](https://github.com/UM-ARK/ARK-ALL-Web/assets/55580370/b67ff532-525b-4338-9c33-a5c4a6a8241f)

**Comment by YanzhenHuang** [comment]
之后改成只接受jpg就行了

**Comment by yyyyyyounger** [comment]
> 之后改成只接受jpg就行了

png和jpg都接受，其實只需增加一個擁有白色背景的、圖片大小的div即可。

**Comment by yyyyyyounger** [comment]
> 之后改成只接受jpg就行了

9bd5bfd36db472e78daa3f24dcee348bf0ff4819

往img標籤添加 `style={{ backgroundColor: '#fff' }}` 解決
